### ISSUE TITLE
Refactor examples

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/examples#103]
TODO:

- [x] use css style sheet (ycar example) for every project
- [x] overall pinned as default
- [x] implement SCTUnit for some examples
- [ ] create examples according to user docu
- [ ] use the same folder hierarchy -> src, srg-gen, test-gen, model 
- [x] delete all warnings out of the projects
- [x] move swift example to labs

**Comment by tkutz** [comment]
> create examples according to user docu
We added lots of additional examples to explain concepts by example, so that is obsolete from my point of view

> use the same folder hierarchy -> src, srg-gen, test-gen, model
I think we can live with slightly different folder structures; different target languages may imply different conventions, so that's also fine from my point of view

=> I will close that issue
